name: Daily Empty Commit

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8:00 AM UTC
  workflow_dispatch:     # Allows manual runs

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make empty change to neuroscan_app.py
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          

          touch neuroscan_app.py
          
          # Add the file explicitly
          git add neuroscan_app.py
          
          # Commit even if there's no real diff
          git commit -m "chore: daily no-op touch on neuroscan_app.py" || echo "No changes to commit"
          git push
